title: "My GitHub Pages Site"
description: "Notes and projects."
url: "https://eliclay1.github.io"
baseurl: "/LocalStorage-Blog-Post"

remote_theme: jekyll/minima
# Remove "theme: minima" entirely â€” do not have both

minima:
  skin: dark  # options: classic, dark, solarized, solarized-dark, auto

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
