title: "LocalStorage - How to use and understand it's magic"
url: "https://eliclay1.github.io"
baseurl: "/LocalStorage-Blog-Post"

# remote_theme: mmistakes/minimal-mistakes
# minimal_mistakes_skin: "dark"
theme: jekyll-theme-hacker

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
